### ISSUE TITLE
Konwencja nazewnictwa

### ISSUE THREAD

**Issue by zbigniewmotyka** [elaniusz/NaukaAngular#5]
https://github.com/elaniusz/NaukaAngular/blob/c4d115228ddaa848cfc29447c6bbd040ca62df15/strona-app/src/app/components/team/team.component.ts#L15

Jeśli chodzi o nazewnictwo rzeczy które występują w kodzie to stosuje się zasadę że z dużymi literami nazywa się klasy, interfejst, enumy itp. natomiast małymi zmienne, instancje klas itp.

```
class Klasa {}
interface JakisModel {}
enum TypWyliczeniowy {}

const obiektJakiejsKlasy: Klasa = new Klasa();
const obiektJakiegosInterfaceu: JakisModel = {};
```

**Comment by elaniusz** [comment]
Ok, natomiast nie łapie co jest czym w tej linijce 15. Domyślam się, że "List" (parametr) może być małą "list" ale getTeams chyba powinno być getTeams bo to metoda.
?

**Comment by zmszaman** [comment]
`getTeams` jest metodą. Metodę też piszemy zaczynając od małej litery. `List` jest parametrem który piszemy też małą literą.
