### ISSUE TITLE
Typ zwracanych danych

### ISSUE THREAD

**Issue by zbigniewmotyka** [elaniusz/NaukaAngular#8]
https://github.com/elaniusz/NaukaAngular/blob/c4d115228ddaa848cfc29447c6bbd040ca62df15/strona-app/src/app/services/team-base.service.ts#L21

Jako że powyżej zwracasz observable to prawdopodobnie docelowo dane będą pochodziły z jakiegoś zewnętrznego źródła (np. z pliku json). W takim wypadku ta metoda też nie będzie w stanie od razy odpowiedzieć danymi a będzie musiała zwrócić observable'a. Przy danych zaszytych na sztywno się to sprawdzi tak jak jest, ale przy innym źródle danych będzie już gorzej :)

**Comment by elaniusz** [comment]
Co więc trzeba zrobić? Pewnie poznam później? jak się nazywa odpowiednia metoda?

**Comment by zmszaman** [comment]
Na ten moment najprościej by było tak jak poniżej.

```
getTeamsById(id: string): Observable<Team> {
    return of(this.TEAMS.find(e => e.id === id));
}
```
