### ISSUE TITLE
Typowanie

### ISSUE THREAD

**Issue by zbigniewmotyka** [elaniusz/NaukaAngular#9]
https://github.com/elaniusz/NaukaAngular/blob/c4d115228ddaa848cfc29447c6bbd040ca62df15/strona-app/src/app/services/team-base.service.ts#L10

1. Właściwość `TEAMS` jest czymś co póki co istnieje tylko po to żeby "udawać" dane pozyskane z jakiegoś źródła. Nie powinniśmy bazować na tej właściwości w innych miejscach aplikacji niż w service'ie TeamBaseService. W tym momencie service masz użyty w komponencie. Gdybyś napisał w nim `this.nazwaWlasciwosciZServiceem.TEAMS` to miałbyś do tego dostęp. Ten dostęp powinien być zablokowany dlatego prawidłowy zapis powinien wyglądać `private TEAMS = [` - przy takim zapisie i próbie użycia tej właściwości w komponencie dostaniesz błąd z typescript co jest właściwym zachowaniem.
2. Tak jak wspomniałem wcześniej właściwości, zmienne itp nazywany małymi literami. Zapis w takiej postaci jak masz tu wg mnie akceptowalny jest tylko dla `InjectionToken<T>` z którymi zapewne nie masz jeszcze do czynienia ;). Uwzględniając punkt 1 o którym wspomniałem prawidłowy zapis to `private teams = [`.
3. Brakuje typowania danych. TO jest ogromna zaleta TypeScript dzięki którym da się wyłapać błędy zanim jeszcze wysypią aplikację. W tym momencie mógłbym sobie zapisać:
```
private teams = [
  new Team('1', 'Marek Michalik', 'Proboszcz parafii Ewangelickiej w Wiśle Czarnem'),
  'a tu se dam jakiś string',
  965
]
```
Co z punktu widzenia typescript będzie ok, ale aplikacja w działaniu się wysypie. Prawidłowa deklaracja właściwości uwzględniają 2 wcześniejsze punkty to: `private teams: Team[] = [` lub `private teams: Array<Team> = [`

**Comment by elaniusz** [comment]
poprawione na:
`private teams = [`

**Comment by zmszaman** [comment]
W dalszym ciągu brakuje otypowania danych. Z punktu widzenia Typescriptu poniższy kod będzie właściwy:

```
private teams = [
    {id: '1', name: 'Marek Michalik', email: 'michalikmm@gmail.com', details: 'Proboszcz parafii Ewangelickiej w Wiśle Czarnem'},
    'a ten string wywali aplikację'
];
```

Powinno być `private teams: Team[] = [` lub `private teams: Array<Team> = [`

**Comment by elaniusz** [comment]
Poprawiłem, mam nadzieję, że teraz dobrze.
